### ISSUE TITLE
rxjava error 

### ISSUE THREAD

**Issue by zpfang9008** [zpfang9008/zpfang9008.github.io#1]
```
FATAL EXCEPTION: RxIoScheduler-2
                                                                    Process: com.fangzp.aboutrx, PID: 29262
                                                                    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/http/HttpEngine;
                                                                        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:232)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                        at okhttp3.RealCall.execute(RealCall.java:60)
                                                                        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
                                                                        at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
                                                                        at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                                                                        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:10150)
                                                                        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.http.HttpEngine" on path: DexPathList[[zip file "/data/app/com.fangzp.aboutrx-2/base.apk"],nativeLibraryDirectories=[/data/app/com.fangzp.aboutrx-2/lib/arm, /data/app/com.fangzp.aboutrx-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:232) 
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) 
                                                                        at okhttp3.RealCall.execute(RealCall.java:60) 
                                                                        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) 
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171) 
                                                                        at rx.Subscriber.setProducer(Subscriber.java:211) 
                                                                        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) 
                                                                        at rx.Subscriber.setProducer(Subscriber.java:205) 
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152) 
                                                                        at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138) 
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:10150) 
                                                                        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
                                                                        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:10150) 
                                                                        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) 
                                                                        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228) 
                                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
                                                                    	Suppressed: java.lang.ClassNotFoundException: okhttp3.internal.http.HttpEngine
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                        		... 31 more
                                                                     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by zpfang9008** [comment]
> Failed resolution of: Lokhttp3/internal/http/HttpEngine;
> HttpLoggingInterceptor error
> 拦截器出错了，用的是3.3.1，需要更新到3.5.0。
